# Generated by Django 5.2.7 on 2025-11-10 06:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField()),
                ('version_label', models.CharField(blank=True, max_length=50)),
                ('filename', models.CharField(max_length=255)),
                ('file_path', models.TextField()),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('metadata_json', models.JSONField(blank=True, null=True)),
                ('thumbnail_path', models.TextField(blank=True)),
                ('web_version_path', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=150, null=True)),
                ('change_notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Asset Version',
                'verbose_name_plural': 'Asset Versions',
                'db_table': 'assets',
                'ordering': ['-version_number'],
            },
        ),
        migrations.CreateModel(
            name='AssetGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('asset_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('3d', '3D Model')], db_index=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.CharField(blank=True, max_length=150, null=True)),
                ('current_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_for_group', to='dam_assets.asset')),
            ],
            options={
                'verbose_name': 'Asset Group',
                'verbose_name_plural': 'Asset Groups',
                'db_table': 'asset_groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='dam_assets.assetgroup'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('upload', 'Upload'), ('update', 'Update'), ('delete', 'Delete'), ('download', 'Download'), ('view', 'View')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('asset_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dam_assets.asset')),
                ('asset_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dam_assets.assetgroup')),
            ],
            options={
                'verbose_name': 'Activity Log',
                'verbose_name_plural': 'Activity Logs',
                'db_table': 'activity_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AssetTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='dam_assets.assetgroup')),
            ],
            options={
                'verbose_name': 'Asset Tag',
                'verbose_name_plural': 'Asset Tags',
                'db_table': 'asset_tags',
                'ordering': ['tag'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['filename'], name='assets_filenam_eff278_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['uploaded_at'], name='assets_uploade_6dfe1e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='asset',
            unique_together={('asset_group', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='assettag',
            index=models.Index(fields=['tag'], name='asset_tags_tag_06ab06_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assettag',
            unique_together={('asset_group', 'tag')},
        ),
    ]
