# Generated by Django 5.2.7 on 2025-11-13 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam_assets', '0002_user_alter_activitylog_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_tokens', to='dam_assets.user')),
            ],
            options={
                'db_table': 'auth_tokens',
            },
        ),
    ]
