# Generated by Django 5.2.7 on 2025-11-24 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dam_assets', '0003_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='thumbnail_path',
            field=models.TextField(blank=True, null=True),
        ),
    ]
